### ISSUE TITLE
Error when Applying core.0019_auto_20160928_1517: django.db.utils.OperationalError: near "SET": syntax error

### ISSUE THREAD

**Issue by Stretsh** [labhackercd/wikilegis#42]
Hey guys,

I'm trying to install Wikilegis on a fresh Ubuntu 16.04.1 server.

I installed build-essential, zlib, libjpeg and Python: 2.7.12 using 'apt', 
updated pip to 8.1.2, installed pillow 3.0.0.

I then ran the commands:

_git clone https://github.com/labhackercd/wikilegis.git_ (git@github.com:labhackercd/wikilegis.git produces a certificate permission error)

_`pip install -r requirements.txt`_ produced a "permission denied error", so I ran _`sudo pip install -r requirements.txt`_

This was successful:
```
Successfully installed Markdown-2.6.6 Pillow-3.0.0 PyJWT-1.4.0 Whoosh-2.7.0 django-cors-headers-1.1.0 django-crispy-forms-1.6.0 django-filter-0.15.2 djangorestframework-3.3.3 easy-thumbnails-2.2 futures-3.0.3 oauthlib-1.0.3 python-decouple-3.0 python-openid-2.2.5 python-social-auth-0.2.13 pytz-2015.6 requests-oauthlib-0.6.1 roman-2.0.0 rules-0.4
```

When I now run _`./manage.py migrate`_ (either as normal user or using sudo) I get the following output:

```
/home/rehuel/wikilegis/wikilegis/core/models.py:5: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic

/home/rehuel/.local/lib/python2.7/site-packages/object_tools/sites.py:45: RemovedInDjango19Warning: django.db.models.get_models is deprecated.
  models = get_models()

/home/rehuel/.local/lib/python2.7/site-packages/django/db/models/__init__.py:55: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
  from . import loading

/home/rehuel/wikilegis/wikilegis/auth2/urls.py:12: RemovedInDjango19Warning: Default value of 'RedirectView.permanent' will change from True to False in Django 1.9. Set an explicit value to silence this warning.
  url(r'^activate/complete/$', ActivationCompleteView.as_view(),

Operations to perform:
  Synchronize unmigrated apps: flat, django_filters, corsheaders, adminsortable2, staticfiles, comments2, messages, compressor, humanize, export, crispy_forms, rest_framework, django_extensions, debug_toolbar, haystack, embed_video, object_tools, image_cropping, rules
  Apply all migrations: core, django_comments, sessions, admin, auth2, registration, sites, auth, default, contenttypes, notification, easy_thumbnails
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying core.0019_auto_20160928_1517...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/rehuel/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/rehuel/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/rehuel/.local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/rehuel/.local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/rehuel/.local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/rehuel/.local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/rehuel/.local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/rehuel/.local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/rehuel/.local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 102, in database_forwards
    self._run_sql(schema_editor, self.sql)
  File "/home/rehuel/.local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 127, in _run_sql
    schema_editor.execute(statement, params=None)
  File "/home/rehuel/.local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/home/rehuel/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/rehuel/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/rehuel/.local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/rehuel/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/home/rehuel/.local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 316, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: near "SET": syntax error
```

I don't know Django, very little Python, so I have no idea where to look or how to debug this. I edited nothing, everything is just as cloned.

**Comment by msfernandes** [comment]
Hi :)

Which database are you using?
I think that migration uses a PostgreSQL specific command: `'SET CONSTRAINTS ALL IMMEDIATE'`. You can comment the lines 15-16 and 23-24 from  `wikilegis/core/migrations/0019_auto_20160928_1517.py` and try to run the migrate command again...

Sorry about that, we'll fix asap!

**Comment by Stretsh** [comment]
No problem. 

Greetings from the Surinamese Parliament...
